export const FETCH_CURRENT_WEATHER_REQUEST = 'weather-app/weather/FETCH_CURRENT_WEATHER_REQUEST';
export const FETCH_CURRENT_WEATHER_SUCCESS = 'weather-app/weather/FETCH_CURRENT_WEATHER_SUCCESS';
export const FETCH_CURRENT_WEATHER_FAILURE = 'weather-app/weather/FETCH_CURRENT_WEATHER_FAILURE';

export const FETCH_FORECAST_REQUEST = 'weather-app/forecast/FETCH_FORECAST_REQUEST';
export const FETCH_FORECAST_SUCCESS = 'weather-app/forecast/FETCH_FORECAST_SUCCESS';
export const FETCH_FORECAST_FAILURE = 'weather-app/forecast/FETCH_FORECAST_FAILURE';